### PR TITLE
Use openssl-probe crate to fix cert errors.

### LINKED ISSUE #183: StarTLS with Lettre fails when using MUSL static builds
https://gist.github.com/jkilpatr/c69d57f7bd84cb65847a5ec7e065ec52

### PR DESCRIPTION
**Pull request by mpapierski**
Reproduced the issue with `linux_build_static.sh` and using a simple `reqwest` HTTPS call.

This should fix #183.

### CODE REVIEW

File: rita/src/client.rs [hunk 1]
```diff
@@ -77,6 +77,8 @@ use rita_client::dashboard::network_endpoints::*;
 use rita_common::dashboard::network_endpoints::*;
 use rita_common::network_endpoints::*;
 
+extern crate openssl_probe;
```
Comment (drozdziak1) [inline rita/src/client.rs]: Put this along with other `extern crate`s. Our imports look like garbage in many places, but let's not make it worse.

File: rita/src/exit.rs [hunk 2]
```diff
@@ -81,6 +81,7 @@ use std::sync::{Arc, RwLock};
 #[cfg(test)]
 use std::sync::Mutex;
 
+extern crate openssl_probe;
```
Comment (drozdziak1) [inline rita/src/exit.rs]: same here

Comment (mpapierski) [reply rita/src/exit.rs]: Makes sense.
